const ROLES = Object.freeze({
  ADMIN: 'admin',
  OWNER: 'owner',
  SUPERVISOR: 'supervisor',
  SPECIAL_SUPERVISOR: 'special_supervisor',
  LABOUR: 'labour',
});

const ADMIN_ROLES = [ROLES.ADMIN];
const OWNER_ROLES = [ROLES.OWNER];
const ADMIN_OR_OWNER_ROLES = [ROLES.ADMIN, ROLES.OWNER];
const FIELD_SUPERVISOR_ROLES = [ROLES.ADMIN, ROLES.SUPERVISOR];
const ASSIGNMENT_ROLES = [ROLES.ADMIN, ROLES.SUPERVISOR, ROLES.SPECIAL_SUPERVISOR];

module.exports = {
  ROLES,
  ADMIN_ROLES,
  OWNER_ROLES,
  ADMIN_OR_OWNER_ROLES,
  FIELD_SUPERVISOR_ROLES,
  ASSIGNMENT_ROLES,
};
