import { StyleSheet } from "react-native";
export const styles = StyleSheet.create({
  /*bnext: {
    marginTop:"auto",
    textAlign:"center",
    backgroundColor:"#000000ff",
    borderRadius:"20",
    //titlecolor:"#FFFFFF",
    fontWeight:"bold",
    width:100,

  },*/
  container: {
    flex: 1,
    padding: 50,
    alignItems: "center",
    justifyContent: "center",
  },
  image: {
    //alignItems:"center",
    //alignSelf:"auto",
    //verticalAlign: 'middle',
    alignItems: "center",
    width: 200,
    height: 200,
    marginTop: 20,
    marginLeft: "auto",
    marginRight: "auto",
  },
  em: {
    textAlign: "center",
    //verticalAlign: 'middle',
    textAlignVertical: "bottom",
    fontFamily: "italic",
    //fontWeight: 'bold',
    fontSize: 18,
    color: "#b6a397ff",
    //textShadowColor: 'rgba(74, 16, 16, 0.75)',
    marginTop: 5,
  },
  head1: {
    fontSize: 55,
    fontFamily: "impact",
    fontWeight: "bold",
    textAlign: "center",
    color: "#eb8934",
    //marginTop:50,
  },
  head: {
    fontSize: 20,
    fontWeight: "bold",
    textAlign: "center",
    marginTop: 5,
  },
  buttonText: {
    backgroundColor: "#eb9834",
    padding: 15,
    marginTop: 30,
    borderRadius: 8,
    textAlign: "center",
    color: "#ffffffff",
    fontSize: 18,
    fontWeight: "bold",
  },
  labelname: {
    color: "#000000",
    //textAlign: "left",
    //alignSelf: "flex-start",
    fontSize: 16,
    marginTop: 5,
    marginBottom: 5,
    fontWeight: "600",
    marginLeft: 8,
  },
  valbox: {
    borderWidth: 1,
    borderColor: "black",
    padding: 10,
    marginLeft: 1,
    marginRight: 1,
    borderRadius: 8,
    color: "black",
    width: "75%",
  },
  backButton: {
    padding: 10,
    marginBottom: 20,
    backgroundColor: "#eb9834",
    color: "#ffffff",
    borderRadius: 8,
  },
  backArrow: {
    color: "#ffffffff",
    fontSize: 32,
    fontWeight: "bold",
  },
  linkstyle: {
    color: "#0000ff",
    textDecorationLine: "underline",
    marginTop: 10,
  },
  header: {
    backgroundColor: '#eb9834',
    padding: 15,
    paddingTop: 40,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  headerTitle: {
    color: 'white',
    fontSize: 20,
    fontWeight: 'bold',
  },
  card: {
    backgroundColor: 'white',
    borderRadius: 8,
    padding: 15,
    marginBottom: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  cardTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 10,
  },
  divider: {
    height: 1,
    backgroundColor: '#eee',
    marginBottom: 10,
  },
});
