import { StyleSheet } from "react-native";

export const getStyles = (isDark: boolean) => StyleSheet.create({
  mainContainer: { flex: 1, backgroundColor: isDark ? "#121212" : "#f6f7fb" },
  container: { flex: 1, backgroundColor: isDark ? "#121212" : "#f6f7fb" },
  content: { padding: 16, paddingBottom: 40 },
  header: { fontSize: 24, fontWeight: "700", marginBottom: 0, color: isDark ? "#fff" : "#000" },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    marginBottom: 12,
    paddingVertical: 6,
  },
  headerRight: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
    justifyContent: "flex-end",
  },
  searchInput: {
    flex: 1,
    height: 40,
    paddingHorizontal: 12,
    backgroundColor: isDark ? "#1e1e1e" : "#fff",
    borderRadius: 20,
    marginRight: 12,
    borderWidth: 1,
    borderColor: isDark ? "#333" : "#e6e6e6",
    color: isDark ? "#fff" : "#000",
    textAlignVertical: "center",
  },
  profileBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#0a84ff",
    alignItems: "center",
    justifyContent: "center",
  },
  profileInitials: { color: "#fff", fontWeight: "700", fontSize: 14 },
  section: { marginTop: 12 },
  sectionTitle: { fontSize: 18, fontWeight: "600", marginBottom: 8, color: isDark ? "#fff" : "#000" },
  card: {
    backgroundColor: isDark ? "#1e1e1e" : "#fff",
    borderRadius: 8,
    padding: 12,
    marginBottom: 10,
    shadowColor: "#000",
    shadowOpacity: isDark ? 0.3 : 0.03,
    shadowRadius: 6,
    elevation: 1,
  },
  /* Manage screen grid and options */
  grid: { flexDirection: "row", flexWrap: "wrap", justifyContent: "space-between" },
  optionCard: {
    width: "48%",
    backgroundColor: isDark ? "#1e1e1e" : "#fff",
    borderRadius: 8,
    padding: 12,
    marginBottom: 12,
    alignItems: "flex-start",
    shadowColor: "#000",
    shadowOpacity: isDark ? 0.3 : 0.03,
    shadowRadius: 6,
    elevation: 1,
  },
  optionIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 8,
    backgroundColor: isDark ? "#333" : "#eef6ff",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 8,
  },
  optionTitle: { fontSize: 14, fontWeight: "700", marginBottom: 4, color: isDark ? "#fff" : "#000" },
  optionDesc: { fontSize: 12, color: isDark ? "#aaa" : "#666" },
  cardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  name: { fontSize: 16, fontWeight: "600", color: isDark ? "#fff" : "#000" },
  role: { fontSize: 12, color: isDark ? "#aaa" : "#666" },
  statsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 10,
  },
  stat: { alignItems: "center", flex: 1 },
  statValue: { fontSize: 15, fontWeight: "700", color: isDark ? "#fff" : "#000" },
  statLabel: { fontSize: 11, color: isDark ? "#aaa" : "#666" },
  actionsRow: { flexDirection: "row", justifyContent: "space-between" },
  actionBtn: {
    flex: 1,
    paddingVertical: 8,
    marginHorizontal: 4,
    backgroundColor: "#0a84ff",
    borderRadius: 6,
    alignItems: "center",
  },
  actionText: { color: "#fff", fontWeight: "600" },
  sectionSummary: { marginTop: 18 },
  summaryRow: { flexDirection: "row", justifyContent: "space-between" },
  summaryText: { fontSize: 14, color: isDark ? "#bbb" : "#333" },
  tabBar: {
    flexDirection: "row",
    backgroundColor: isDark ? "#1e1e1e" : "#fff",
    borderTopWidth: 1,
    borderTopColor: isDark ? "#333" : "#e6e6e6",
    paddingVertical: 8,
    paddingHorizontal: 4,
    elevation: 8,
  },
  tabBtn: {
    flex: 1,
    paddingVertical: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  activeTab: {
    borderBottomWidth: 3,
    borderBottomColor: "#0a84ff",
  },
  tabIcon: { marginBottom: 2 },
  tabLabel: { fontSize: 10, color: isDark ? "#aaa" : "#666", fontWeight: "500" },
  activeTabText: { color: isDark ? "#4da6ff" : "#0a84ff", fontWeight: "700" },
});

// Default export for backward compatibility where styles is used directly without useTheme
export const styles = getStyles(false);